---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Call-RestAPI-Ext
  title: Call RestAPI testing for external post/get
  description: Testing
  lifecycle:
    - development
  
spec:
  owner: user:default/michel.leijdekker
  type: service

  parameters:
    - title: Provide API URI to call
      properties:
        URI:
          title: Get URI
          type: string
          description: The path you want to get on your backstage instance
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: call_external_api
      name: call external api
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/simple-example'
        headers:
          content-type: 'application/json'   

    # The import flow debug step, enable it for debugging        
    - id: log-debug
      name: Debug Logs
      action: debug:log
      input:
        message: "Fetched catelog entities for user and groups"
        API_ResponseBody: ${{ steps.call_external_api.output.body }}
        API_Code: ${{ steps.call_external_api.output.code }}

  output:
      getResponse: '{{ steps.call_external_api.output.body }}'
      getCode: '{{ steps.call_external_api.output.code }}'
      getHeaders: '{{ steps.call_external_api.output.headers }}'