---
apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: Call-RestAPI
  title: Call RestAPI testing for post/get
  description: Testing get functionality with get
  lifecycle:
    - development
  
spec:
  owner: michel.leijdekker
  type: service

  parameters:
    - title: Provide API URI to call
      properties:
        URI:
          title: Get URI
          type: string
          description: The path you want to get on your backstage instance
          ui:autofocus: true
          ui:options:
            rows: 5

  steps:
    - id: call-devhub-api
      name: call devhub api
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/catalog/entities?filter=kind=user&filter=kind=group'
        headers:
          content-type: 'application/json'

  # The import flow debug step, enable it for debugging  
    - id: log-debug1
      name: Debug Logs
      action: debug:log
      input:
        message: "Fetched catelog entities for user and groups"
        API_Response: ${{ steps.call-devhub-api.output.body[1]}}
  
    - id: call-external-api
      name: call external api
      action: http:backstage:request
      input:
        method: 'GET'
        path: '/proxy/api/proxy/simple-example'
        headers:
          content-type: 'application/json'   

    # The import flow debug step, enable it for debugging       
    - id: log-debug2
      name: Debug Logs
      action: debug:log
      input:
        message: "Fetched catelog entities for user and groups"
        API_Response: ${{ steps.call-external-api.output.body[0]}}

  output:
      getResponse1: '{{ steps.call-devhub-api.output.body }}'
      getResponse2: '{{ steps.call-external-api.output.body }}'
      getCode1: '{{ steps.call-devhub-api.output.code }}'
      getCode2: '{{ steps.call-external-api.output.code }}'
      getHeaders1: '{{ steps.call-devhub-api.output.headers }}'
      getHeaders2: '{{ steps.call-external-api.output.headers }}'